server:
  servlet:
    context-path: /survey-platform
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  profiles:
    active: ${PROFILE_ACTIVE}
  application:
    name: survey-platform
